server:
  port: 8083

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bidding_db
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: bid-processing-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.auction.bidding.model"

auth:
  service:
    base-url: http://localhost:8081/api/auth

users:
  service:
    base-url: http://localhost:8081/api/users

auction:
  service:
    base-url: http://localhost:8082/api/auctions

kafka:
  topic:
    bids: bids-topic

bidding:
  rate-limit:
    interval: 60 # seconds